#!/bin/sh
. watson-env.conf
cf ic run -p 80 -m 512 -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_USERNAME=${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_USERNAME} -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_PASSWORD=${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_PASSWORD} -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_URL=${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_URL} -e APP_SECRET=${APP_SECRET} registry.ng.bluemix.net/${DOCKER_NS}/watsonproxy
