#!/bin/sh
. watson-env.conf
docker run -d -p 80:80 -e APP_SECRET=${APP_SECRET} -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_USERNAME="${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_USERNAME}" -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_PASSWORD="${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_PASSWORD}" -e VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_URL=${VCAP_SERVICES_SPEECH_TO_TEXT_0_CREDENTIALS_URL} -t ${DOCKER_NS}/watsonproxy
